[package]
name = "comyfcast-server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.92"
axum = { version = "0.7.7", features = ["http2", "macros", "ws"] }
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "tracing-log"] }
